# Generated by Django 2.2.6 on 2019-10-25 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='indexInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='DictWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTexto', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('indexInv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatmentFile.indexInv')),
            ],
        ),
    ]
