# Generated by Django 2.2.6 on 2019-11-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='docfile',
            field=models.FileField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
