# Generated by Django 2.2.6 on 2019-11-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatmentFile', '0002_texto_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='docfile',
        ),
    ]
